[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "garminconnect>=0.2.38",
    "python-dotenv>=1.2.1",
    "pydantic>=2.0.0",
    "garmin-fit-sdk>=21.188.0",
]

[dependency-groups]
dev = [
    "ty>=0.0.13",
]
